name: Publish on GitHub Pages

on: push

permissions:
  contents: write

jobs:
  publish_github_pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker://pandoc/core:2.9
        with:
          args: "-s omz-git-aliases.md -c tufte.css -o index.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
